"""initial

Revision ID: 6662a4db236d
Revises: 
Create Date: 2026-02-10 23:49:05.473563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6662a4db236d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index(op.f('ix_drivers_driver_id'), 'drivers', ['driver_id'], unique=False)
    op.create_index(op.f('ix_drivers_driver_name'), 'drivers', ['driver_name'], unique=False)
    op.create_table('trucks',
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('truck_id')
    )
    op.create_index(op.f('ix_trucks_plate_number'), 'trucks', ['plate_number'], unique=False)
    op.create_index(op.f('ix_trucks_truck_id'), 'trucks', ['truck_id'], unique=False)
    op.create_index(op.f('ix_trucks_unit_number'), 'trucks', ['unit_number'], unique=True)
    op.create_index(op.f('ix_trucks_vin'), 'trucks', ['vin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trucks_vin'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_unit_number'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_truck_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_plate_number'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_drivers_driver_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_driver_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
